#!/bin/bash


# NOTE -- Remember that this is run before EVERY PUSH. Be very
#         careful about what goes in here. If it gets slow (for some
#         squishy, subjective value of "slow") people will start using
#         --no-verify, which defeats the whole purpose of this file.
